apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-elasticsearch-data-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  storageClassName: local-storage
  hostPath:
    path: /data/elk/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-elasticsearch-data-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  storageClassName: local-storage
  hostPath:
    path: /data/elk1/
---
