---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-application
  namespace: elasticsearch
data:
  logstash.conf: |-
    input {
      tcp {
        port => 5044
      }
    }
    output {
      elasticsearch {
        hosts => "10.233.36.57:9200"
      }
    }
  logstash.yml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash-application
  namespace: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash-application
    spec:
      containers:
      - image: docker.elastic.co/logstash/logstash-oss:6.2.4
        name: logstash-application
        ports:
        - name: http
          containerPort: 5044
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          readOnly: true
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
          readOnly: true
        args:
        - -f
        - /usr/share/logstash/pipeline/logstash.conf
        resources:
          limits:
            memory: 2Gi
            cpu: "200m"
          requests:
            memory: 2Gi
            cpu: "200m"
      volumes:
      - name: pipeline
        configMap:
          name: logstash-application
          items:
          - key: logstash.conf
            path: logstash.conf
      - name: config
        configMap:
          name: logstash-application
          items:
          - key: logstash.yml
            path: logstash.yml
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-application
  namespace: elasticsearch
  labels:
    app: logstash-application
spec:
  type: LoadBalancer
  selector:
    app: logstash-application
  ports:
  - name: http
    port: 5044
    protocol: TCP
  - name: check
    port: 9600
    protocol: TCP
